name: download_file
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13.0
  - pip=24.0
  - requests=2.31.0
  - pyarrow=15.0.0
  - pip:
      - mlflow==2.9.0
      - wandb==0.16.3
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components
